event_types = [
    "baking",
    "calibration",
    "check-in",
    "check-out",
    "cleaning",
    "compression",
    "decompression",
    "editing",
    "format-identification",
    "ingest",
    "inspection",
    "registration",
    "transcoding",
    "transcription",
    "transfer",
    "transform",
    "digital-transfer",
    "digitization",
    "quality-control",
    "repair",
    "validation",
    "migration",
    "creation",
]

relationship_types = [
    "structural",
]

object_identifier_types = [
    # Main keys
    "UUID",
    "MEEMOO-LOCAL-ID",
    "MEEMOO-PID",
    # Overige lokale CP ID - https://developer.meemoo.be/docs/metadata/viaa/algemeen.html#mogelijke-sleutels
    "Acquisition_number",
    "Alternative_number",
    "Analoge_drager",
    "Api",
    "Ardome",
    "Basis",
    "Bestandsnaam",
    "DataPID",
    "Historical_carrier",
    "Historical_record_number",
    "Inventarisnummer",
    "MEDIA_ID",
    "Object_number",
    "Pdf",
    "PersistenteURI_Record",
    "PersistenteURI_VKC_Record",
    "PersistenteURI_VKC_Werk",
    "PersistenteURI_Werk",
    "Priref",
    "Vaf_ID",
    "Topstuk_ID",
    "Word_ID",
    "WorkPID",
]
