[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "meemoo-sip-validator"
version = "0.1.0"
description = "A library that validates if a package is a valid meemoo SIP"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "py-commons-ip>=0.0.1,<1"
]
classifiers = [
  "Programming Language :: Python :: 3.12",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.12.0,<0.13",
    "build>=1.2.2,<2.0.0",
    "twine>=6.1.0,<7.0.0",
]

[tool.setuptools.package-data]
"meemoo_sip_validator" = ["*"]