# Generated via script.

from .. import (
    MeemooSIPConstraint,
    MeemooSIPConstraintCardinality,
    MeemooSIPConstraintObligation,
    MeemooSIPConstraintSIPLevel,
    MeemooSIPConstraintDatatype,
    MeemooSIPConstraintXMLNodeType,
)

bacp1 = MeemooSIPConstraint(
    "BACP1",
    "There MUST be exactly one IE.",
    MeemooSIPConstraintCardinality.UNSPECIFIED,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.GENERAL,
    "/",
    "",
)
bacp2 = MeemooSIPConstraint(
    "BACP2",
    "The IE MUST be represented by exactly one representation.",
    MeemooSIPConstraintCardinality.UNSPECIFIED,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.GENERAL,
    "/",
    "",
)
bacp3 = MeemooSIPConstraint(
    "BACP3",
    "The representation MUST contain at least one file.",
    MeemooSIPConstraintCardinality.UNSPECIFIED,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.GENERAL,
    "/",
    "",
)
bacp4 = MeemooSIPConstraint(
    "BACP4",
    "Preservation metadata MUST be limited to the PREMIS metadata schema.",
    MeemooSIPConstraintCardinality.UNSPECIFIED,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.GENERAL,
    "/",
    "",
)
bacp5 = MeemooSIPConstraint(
    "BACP5",
    "There MUST be preservation metadata at the package level in the `preservation/premis.xml` file.",
    MeemooSIPConstraintCardinality.UNSPECIFIED,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.GENERAL,
    "/",
    "",
)
bacp6 = MeemooSIPConstraint(
    "BACP6",
    "There MUST be preservation metadata at the representation level in the `preservation/premis.xml` file.",
    MeemooSIPConstraintCardinality.UNSPECIFIED,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.GENERAL,
    "/",
    "",
)
bacp7 = MeemooSIPConstraint(
    "BACP7",
    'The value of element `premis:premis/premis:object[@xsi:type="premis:file"]/premis:objectCharacteristics/premis:fixity/premis:messageDigestAlgorithm` MUST be set to `MD5`.',
    MeemooSIPConstraintCardinality.UNSPECIFIED,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.GENERAL,
    "/",
    "",
)
bacp8 = MeemooSIPConstraint(
    "BACP8",
    'The value of attribute `premis:premis/premis:object[@xsi:type="premis:file"]/premis:objectCharacteristics/premis:fixity/premis:messageDigestAlgorithm/@valueURI` MUST be set to `"http://id.loc.gov/vocabulary/preservation/cryptographicHashFunctions/md5"`.',
    MeemooSIPConstraintCardinality.UNSPECIFIED,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.GENERAL,
    "/",
    "",
)
bacp9 = MeemooSIPConstraint(
    "BACP9",
    "The `csip:CONTENTINFORMATIONTYPE` attribute MUST be set to `OTHER` and the `csip:OTHERCONTENTINFORMATIONTYPE` attribute MUST be set to `https://data.hetarchief.be/id/sip/2.1/basic`.",
    MeemooSIPConstraintCardinality.UNSPECIFIED,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.GENERAL,
    "/",
    "",
)
bacp10 = MeemooSIPConstraint(
    "BACP10",
    "The `mets/dmdSec/mdRef/@MDTYPE` attribute MUST be set to `OTHER` and `mets/dmdSec/mdRef/@OTHERMDTYPE` attribute must be set to `DC+SCHEMA`.",
    MeemooSIPConstraintCardinality.UNSPECIFIED,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.GENERAL,
    "/",
    "",
)
bacp11 = MeemooSIPConstraint(
    "BACP11",
    "There MUST NOT be any descriptive metadata at the representation level.",
    MeemooSIPConstraintCardinality.UNSPECIFIED,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.GENERAL,
    "/",
    "",
)
bacp12 = MeemooSIPConstraint(
    "BACP12",
    "The `/descriptive` directory at the package level MUST contain exactly one metadata file `dc+schema.xml` that describes the IE.",
    MeemooSIPConstraintCardinality.UNSPECIFIED,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.GENERAL,
    "/",
    "",
)
bacp13 = MeemooSIPConstraint(
    "BACP13",
    "The `dc+schema.xml` file MUST use the `<metadata/>` tag as its root element.",
    MeemooSIPConstraintCardinality.UNSPECIFIED,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.GENERAL,
    "/",
    "",
)
bacp14 = MeemooSIPConstraint(
    "BACP14",
    "The `dc+schema.xml` file MUST declare the `http://purl.org/dc/terms/` (dcterms), `https://schema.org/` (schema), `http://www.w3.org/2001/XMLSchema-instance` (xsi) and `http://id.loc.gov/datatypes/edtf/` (edtf) namespaces in its root element.",
    MeemooSIPConstraintCardinality.UNSPECIFIED,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.GENERAL,
    "/",
    "",
)
bacp15 = MeemooSIPConstraint(
    "BACP15",
    "The `dc+schema.xml` file MUST declare `https://data.hetarchief.be/id/sip/2.1/basic` as default namespace in its root element.",
    MeemooSIPConstraintCardinality.UNSPECIFIED,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.GENERAL,
    "/",
    "",
)
bacp16 = MeemooSIPConstraint(
    "BACP16",
    "Descriptive metadata in `dc+schema.xml` MUST be limited to the [DCTERMS](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/) and [SCHEMA](http://schema.org) elements outlined in the table below.",
    MeemooSIPConstraintCardinality.UNSPECIFIED,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.GENERAL,
    "/",
    "",
)
bacp17 = MeemooSIPConstraint(
    "BACP17",
    "The `dc+schema.xml` file MUST adhere to the restrictions on cardinality of terms outlined in the table below; if a term is not listed with a restriction on cardinality, it MAY be used multiple times.",
    MeemooSIPConstraintCardinality.UNSPECIFIED,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.GENERAL,
    "/",
    "",
)
bacp18 = MeemooSIPConstraint(
    "BACP18",
    "The `dc+schema.xml` file MUST contain a shared ID with a PREMIS object in the `preservation/premis.xml` file, stored in the `<dcterms:identifier>` element (see [next section](#connecting-the-descriptive-metadata-to-premis)).",
    MeemooSIPConstraintCardinality.UNSPECIFIED,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.GENERAL,
    "/",
    "",
)
bacp19 = MeemooSIPConstraint(
    "BACP19",
    "The `dc+schema.xml` file MUST NOT contain additional IDs besides the shared ID in the `<dcterms:identifier>`; these MUST be added in the `preservation/premis.xml` file.",
    MeemooSIPConstraintCardinality.UNSPECIFIED,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.GENERAL,
    "/",
    "",
)
bacp20 = MeemooSIPConstraint(
    "BACP20",
    "Some descriptive metadata elements of datatype [String]({{ site.baseurl }}{% link docs/diginstroom/sip/2.1/2_terminology.md %}#string) MUST contain an attribute `@xml:lang` that indicates the language of the metadata element's value (in order to, for example, specify a title or description in multiple languages); these are indicated with `[@xml:lang=*]` in the table below. Other elements MUST NOT contain this attribute.",
    MeemooSIPConstraintCardinality.UNSPECIFIED,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.GENERAL,
    "/",
    "",
)
bacp21 = MeemooSIPConstraint(
    "BACP21",
    "The value of the `@xml:lang` attribute MUST be a valid [IETF BCP 47 language tag](https://www.rfc-editor.org/info/bcp47)(see [here](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry) for a list).",
    MeemooSIPConstraintCardinality.UNSPECIFIED,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.GENERAL,
    "/",
    "",
)
bacp22 = MeemooSIPConstraint(
    "BACP22",
    "The root element for descriptive metadata in [DCTERMS](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/). This root element MUST declare the XML schema namespaces `http://purl.org/dc/terms/` (dcterms), `http://www.w3.org/2001/XMLSchema-instance` (xsi) and `http://id.loc.gov/datatypes/edtf/` (edtf), and the default namespace `https://data.hetarchief.be/id/sip/2.1/basic`.",
    MeemooSIPConstraintCardinality.EXACTLY_ONE,
    MeemooSIPConstraintObligation.MUST,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata",
)
bacp23 = MeemooSIPConstraint(
    "BACP23",
    "A name given to the Intellectual Entity. The `title` term MAY only be used multiple times when it uses a different language. The applied language MUST be provided by a `@xml:lang` attribute (see requirements above). There MUST always be an entry in Dutch with `@xml:lang` set to `nl`.",
    MeemooSIPConstraintCardinality.EXACTLY_ONE,
    MeemooSIPConstraintObligation.MUST,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/dcterms:title[@xml:lang=*]",
)
bacp24 = MeemooSIPConstraint(
    "BACP24",
    "An alternative to the main title given to the Intellectual Entity.The `alternative` term MAY only be used multiple times when it uses a different language. The applied language MUST be provided by a `@xml:lang` attribute (see requirements above). There MUST always be an entry in Dutch with `@xml:lang` set to `nl`.",
    MeemooSIPConstraintCardinality.ZERO_OR_MORE,
    MeemooSIPConstraintObligation.MAY,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/dcterms:alternative[@xml:lang=*]",
)
bacp25 = MeemooSIPConstraint(
    "BACP25",
    "An unambiguous and unique reference to the Intellectual Entity/Entities present in the SIP.This identifier MUST be used to establish a link between the `dc+schema.xml` file and the relevant PREMIS object in the `preservation/premis.xml` file.",
    MeemooSIPConstraintCardinality.EXACTLY_ONE,
    MeemooSIPConstraintObligation.MUST,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.ID,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/dcterms:identifier",
)
bacp26 = MeemooSIPConstraint(
    "BACP26",
    "Duration in time of the Intellectual Entity.",
    MeemooSIPConstraintCardinality.AT_MOST_ONE,
    MeemooSIPConstraintObligation.MAY,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.XSD_DURATION,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/dcterms:extent",
)
bacp27 = MeemooSIPConstraint(
    "BACP27",
    "The moment that the Intellectual Entity became available.",
    MeemooSIPConstraintCardinality.AT_MOST_ONE,
    MeemooSIPConstraintObligation.MAY,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.XSD_DATETIME,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/dcterms:available",
)
bacp28 = MeemooSIPConstraint(
    "BACP28",
    "An account of the Intellectual Entity.The `description` term MAY only be used multiple times when it uses a different language. The applied language MUST be provided by a `@xml:lang` attribute (see requirements above). There MUST always be an entry in Dutch with `@xml:lang` set to `nl`.",
    MeemooSIPConstraintCardinality.EXACTLY_ONE,
    MeemooSIPConstraintObligation.MUST,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/dcterms:description[@xml:lang=*]",
)
bacp29 = MeemooSIPConstraint(
    "BACP29",
    "A long description of the Intellectual Entity.The `abstract` term MAY only be used multiple times when it uses a different language. The applied language MUST be provided by a `@xml:lang` attribute (see requirements above). If the element is present, there MUST always be an entry in Dutch with `@xml:lang` set to `nl`.",
    MeemooSIPConstraintCardinality.AT_MOST_ONE,
    MeemooSIPConstraintObligation.MAY,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/dcterms:abstract[@xml:lang=*]",
)
bacp30 = MeemooSIPConstraint(
    "BACP30",
    "Creation date of the Intellectual Entity.",
    MeemooSIPConstraintCardinality.EXACTLY_ONE,
    MeemooSIPConstraintObligation.MUST,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.EDTF,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/dcterms:created",
)
bacp31 = MeemooSIPConstraint(
    "BACP31",
    "Date of formal issuance of the Intellectual Entity.",
    MeemooSIPConstraintCardinality.AT_MOST_ONE,
    MeemooSIPConstraintObligation.MAY,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.EDTF,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/dcterms:issued",
)
bacp32 = MeemooSIPConstraint(
    "BACP32",
    "A publisher of the Intellectual Entity. This element is an alias for `metadata/schema:creator` without the attribute `@schema:roleName`.",
    MeemooSIPConstraintCardinality.ZERO_OR_MORE,
    MeemooSIPConstraintObligation.MAY,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/dcterms:publisher",
)
bacp33 = MeemooSIPConstraint(
    "BACP33",
    "A contributor to the Intellectual Entity. This element is an alias for `metadata/schema:creator` without the attribute `@schema:roleName`.",
    MeemooSIPConstraintCardinality.ZERO_OR_MORE,
    MeemooSIPConstraintObligation.MAY,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/dcterms:contributor",
)
bacp34 = MeemooSIPConstraint(
    "BACP34",
    "An author or creator of the Intellectual Entity. This element is an alias for `metadata/schema:creator` without the attribute `@schema:roleName`.",
    MeemooSIPConstraintCardinality.ZERO_OR_MORE,
    MeemooSIPConstraintObligation.MAY,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/dcterms:creator",
)
bacp35 = MeemooSIPConstraint(
    "BACP35",
    "Spatial coverage information on the Intellectual Entity",
    MeemooSIPConstraintCardinality.ZERO_OR_MORE,
    MeemooSIPConstraintObligation.MAY,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/dcterms:spatial",
)
bacp36 = MeemooSIPConstraint(
    "BACP36",
    "Temporal coverage information on the Intellectual Entity",
    MeemooSIPConstraintCardinality.ZERO_OR_MORE,
    MeemooSIPConstraintObligation.MAY,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/dcterms:temporal",
)
bacp37 = MeemooSIPConstraint(
    "BACP37",
    "Subjects or keywords related to the Intellectual Entity. If the element is present, the applied language MUST be provided by a `@xml:lang` attribute (see requirements above) and there MUST always be an entry in Dutch with `@xml:lang` set to `nl`.",
    MeemooSIPConstraintCardinality.ZERO_OR_MORE,
    MeemooSIPConstraintObligation.SHOULD,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/dcterms:subject[@xml:lang=*]",
)
bacp38 = MeemooSIPConstraint(
    "BACP38",
    "The language that the Intellectual Entity is in.",
    MeemooSIPConstraintCardinality.ZERO_OR_MORE,
    MeemooSIPConstraintObligation.SHOULD,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.BCP47,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/dcterms:language",
)
bacp39 = MeemooSIPConstraint(
    "BACP39",
    "A legal document giving official permission to meemoo, end users of the meemoo platforms, or any other user, to do something with the Intellectual Entity.",
    MeemooSIPConstraintCardinality.ZERO_OR_MORE,
    MeemooSIPConstraintObligation.SHOULD,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/dcterms:license",
)
bacp40 = MeemooSIPConstraint(
    "BACP40",
    "The person or ogranization that holds the copyright to the Intellectual Entity. The `rightsHolder` term MAY only be used multiple times when it uses a different language. The applied language MUST be provided by a `@xml:lang` attribute (see requirements above). If the element is present, there MUST always be an entry in Dutch with `@xml:lang` set to `nl`.",
    MeemooSIPConstraintCardinality.AT_MOST_ONE,
    MeemooSIPConstraintObligation.SHOULD,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/dcterms:rightsHolder[@xml:lang=*]",
)
bacp41 = MeemooSIPConstraint(
    "BACP41",
    "A copyright notice on the Intellectual Entity. The `rights` term MAY only be used multiple times when it uses a different language. The applied language MUST be provided by a `@xml:lang` attribute (see requirements above). If the element is present, there MUST always be an entry in Dutch with `@xml:lang` set to `nl`.",
    MeemooSIPConstraintCardinality.AT_MOST_ONE,
    MeemooSIPConstraintObligation.SHOULD,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/dcterms:rights[@xml:lang=*]",
)
bacp42 = MeemooSIPConstraint(
    "BACP42",
    "The classification of this Intellectual Entity .",
    MeemooSIPConstraintCardinality.EXACTLY_ONE,
    MeemooSIPConstraintObligation.MAY,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/dcterms:type",
)
bacp43 = MeemooSIPConstraint(
    "BACP43",
    "The format of this Intellectual Entity .",
    MeemooSIPConstraintCardinality.EXACTLY_ONE,
    MeemooSIPConstraintObligation.MAY,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/dcterms:format",
)
bacp44 = MeemooSIPConstraint(
    "BACP44",
    "The creator/author of the digitally reproduced artwork. This element is an alias for `metadata/dcterms:creator`.",
    MeemooSIPConstraintCardinality.ZERO_OR_MORE,
    MeemooSIPConstraintObligation.MAY,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/schema:creator",
)
bacp45 = MeemooSIPConstraint(
    "BACP45",
    "An agent that has contributed to the digitally reproduced artwork. This element is an alias for `metadata/dcterms:contributor`.",
    MeemooSIPConstraintCardinality.ZERO_OR_MORE,
    MeemooSIPConstraintObligation.MAY,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/schema:contributor",
)
bacp46 = MeemooSIPConstraint(
    "BACP46",
    "The publisher of the digitally reproduced artwork. This element is an alias for `metadata/dcterms:publisher`.",
    MeemooSIPConstraintCardinality.ZERO_OR_MORE,
    MeemooSIPConstraintObligation.MAY,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/schema:publisher",
)
bacp47 = MeemooSIPConstraint(
    "BACP47",
    "The role with which the creator, publisher, or contributor was involved in creating, publishing or contributing to the digitally reproduced artwork.",
    MeemooSIPConstraintCardinality.AT_MOST_ONE,
    MeemooSIPConstraintObligation.SHOULD,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ATTRIBUTE,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/(schema:creator|schema:publisher|schema:contributor)/@schema:roleName",
)
bacp48 = MeemooSIPConstraint(
    "BACP48",
    "The name of the creator, publisher, or contributor. The `name` term MAY only be used multiple times when it uses a different language. The applied language MUST be provided by a `@xml:lang` attribute (see requirements above). If the element is present, there MUST always be an entry in Dutch with `@xml:lang` set to `nl`.",
    MeemooSIPConstraintCardinality.EXACTLY_ONE,
    MeemooSIPConstraintObligation.SHOULD,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/(schema:creator|schema:publisher|schema:contributor)/schema:name[@xml:lang=*]",
)
bacp49 = MeemooSIPConstraint(
    "BACP49",
    "The creator, publisher, or contributor's date of birth.",
    MeemooSIPConstraintCardinality.AT_MOST_ONE,
    MeemooSIPConstraintObligation.SHOULD,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.EDTF,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/(schema:creator|schema:publisher|schema:contributor)/schema:birthDate",
)
bacp50 = MeemooSIPConstraint(
    "BACP50",
    "The creator, publisher, or contributor's date of death.",
    MeemooSIPConstraintCardinality.AT_MOST_ONE,
    MeemooSIPConstraintObligation.SHOULD,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.EDTF,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/(schema:creator|schema:publisher|schema:contributor)/schema:deathDate",
)
bacp51 = MeemooSIPConstraint(
    "BACP51",
    "The measured height of the physical artwork.",
    MeemooSIPConstraintCardinality.AT_MOST_ONE,
    MeemooSIPConstraintObligation.MUST,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/schema:height",
)
bacp52 = MeemooSIPConstraint(
    "BACP52",
    "The measure width of the physical artwork.",
    MeemooSIPConstraintCardinality.AT_MOST_ONE,
    MeemooSIPConstraintObligation.MAY,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/schema:width",
)
bacp53 = MeemooSIPConstraint(
    "BACP53",
    "The measured depth of the physical artwork.",
    MeemooSIPConstraintCardinality.AT_MOST_ONE,
    MeemooSIPConstraintObligation.MAY,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/schema:depth",
)
bacp54 = MeemooSIPConstraint(
    "BACP54",
    "The measured weight of the physical artwork.",
    MeemooSIPConstraintCardinality.AT_MOST_ONE,
    MeemooSIPConstraintObligation.MAY,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/schema:weight",
)
bacp55 = MeemooSIPConstraint(
    "BACP55",
    "The height, width, depth, or weight measurement value.",
    MeemooSIPConstraintCardinality.EXACTLY_ONE,
    MeemooSIPConstraintObligation.MUST,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.FLOAT,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/(schema:height|schema:width|schema:depth|schema:weight)/schema:value",
)
bacp56 = MeemooSIPConstraint(
    "BACP56",
    "The unit of length measurement given using the [UN/CEFACT Common Code (3 characters)](http://wiki.goodrelations-vocabulary.org/Documentation/UN/CEFACT_Common_Codes).",
    MeemooSIPConstraintCardinality.AT_MOST_ONE,
    MeemooSIPConstraintObligation.MAY,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/(schema:height|schema:width|schema:depth)/schema:unitCode",
)
bacp57 = MeemooSIPConstraint(
    "BACP57",
    "The unit of weight measurement given using the [UN/CEFACT Common Code (3 characters)](http://wiki.goodrelations-vocabulary.org/Documentation/UN/CEFACT_Common_Codes), which MUST be set to `KGM` (kilograms).",
    MeemooSIPConstraintCardinality.AT_MOST_ONE,
    MeemooSIPConstraintObligation.MUST,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/schema:weight/schema:unitCode",
)
bacp58 = MeemooSIPConstraint(
    "BACP58",
    "A string or text indicating the unit of the height or width measurement value. Useful if you cannot provide a standard unit code for `schema:unitCode`.",
    MeemooSIPConstraintCardinality.EXACTLY_ONE,
    MeemooSIPConstraintObligation.MAY,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/(schema:height|schema:width|schema:depth)/schema:unitText",
)
bacp59 = MeemooSIPConstraint(
    "BACP59",
    "A string or text indicating the unit of the weight measurement value, which MUST be set to `kg` (kilograms). Useful if you cannot provide a standard unit code for `schema:unitCode`.",
    MeemooSIPConstraintCardinality.EXACTLY_ONE,
    MeemooSIPConstraintObligation.MUST,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/schema:weight/schema:unitText",
)
bacp60 = MeemooSIPConstraint(
    "BACP60",
    "The material used to create the physical artwork, e.g. Oil, Watercolour, Acrylic, Linoprint, Marble, Cyanotype, Digital, Lithograph, DryPoint, Intaglio, Pastel, Woodcut, Pencil, Mixed Media, etc. The applied language MUST be provided by a `@xml:lang` attribute (see requirements above). There MUST always be an entry in Dutch with `@xml:lang` set to `nl`.",
    MeemooSIPConstraintCardinality.ZERO_OR_MORE,
    MeemooSIPConstraintObligation.MAY,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/schema:artMedium[@xml:lang=*]",
)
bacp61 = MeemooSIPConstraint(
    "BACP61",
    "The type of artform, e.g. Painting, Drawing, Sculpture, Print, Photograph, Assemblage, Collage, etc. The applied language MUST be provided by a `@xml:lang` attribute (see requirements above). There MUST always be an entry in Dutch with `@xml:lang` set to `nl`.",
    MeemooSIPConstraintCardinality.ZERO_OR_MORE,
    MeemooSIPConstraintObligation.MAY,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/schema:artform[@xml:lang=*]",
)
bacp62 = MeemooSIPConstraint(
    "BACP62",
    "Indicates an episode that this item is part of.",
    MeemooSIPConstraintCardinality.ZERO_OR_MORE,
    MeemooSIPConstraintObligation.MUST,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/schema:isPartOf[@xsi:type=schema:Episode]",
)
bacp63 = MeemooSIPConstraint(
    "BACP63",
    "The name of the episode. The `name` term MAY only be used multiple times when it uses a different language. The applied language MUST be provided by a `@xml:lang` attribute (see requirements above). If the element is present, there MUST always be an entry in Dutch with `@xml:lang` set to `nl`.",
    MeemooSIPConstraintCardinality.EXACTLY_ONE,
    MeemooSIPConstraintObligation.MAY,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/schema:isPartOf[@xsi:type=schema:Episode]/schema:name[@xml:lang=*]",
)
bacp64 = MeemooSIPConstraint(
    "BACP64",
    "Indicates an archive that this item is part of.",
    MeemooSIPConstraintCardinality.ZERO_OR_MORE,
    MeemooSIPConstraintObligation.MUST,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/schema:isPartOf[@xsi:type=schema:ArchiveComponent]",
)
bacp65 = MeemooSIPConstraint(
    "BACP65",
    "The name of the archive. The `name` term MAY only be used multiple times when it uses a different language. The applied language MUST be provided by a `@xml:lang` attribute (see requirements above). If the element is present, there MUST always be an entry in Dutch with `@xml:lang` set to `nl`.",
    MeemooSIPConstraintCardinality.EXACTLY_ONE,
    MeemooSIPConstraintObligation.MAY,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/schema:isPartOf[@xsi:type=schema:ArchiveComponent]/schema:name[@xml:lang=*]",
)
bacp66 = MeemooSIPConstraint(
    "BACP66",
    "Indicates a series that this item is part of.",
    MeemooSIPConstraintCardinality.ZERO_OR_MORE,
    MeemooSIPConstraintObligation.MUST,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/schema:isPartOf[@xsi:type=schema:CreativeWorkSeries]",
)
bacp67 = MeemooSIPConstraint(
    "BACP67",
    "The name of the series. The `name` term MAY only be used multiple times when it uses a different language. The applied language MUST be provided by a `@xml:lang` attribute (see requirements above). If the element is present, there MUST always be an entry in Dutch with `@xml:lang` set to `nl`.",
    MeemooSIPConstraintCardinality.EXACTLY_ONE,
    MeemooSIPConstraintObligation.MAY,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/schema:isPartOf[@xsi:type=schema:CreativeWorkSeries]/schema:name[@xml:lang=*]",
)
bacp68 = MeemooSIPConstraint(
    "BACP68",
    "The number of the series.",
    MeemooSIPConstraintCardinality.AT_MOST_ONE,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.INTEGER,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/schema:isPartOf[@xsi:type=schema:CreativeWorkSeries]/schema:position",
)
bacp69 = MeemooSIPConstraint(
    "BACP69",
    "Indicates a subseries that is part of this series.",
    MeemooSIPConstraintCardinality.ZERO_OR_MORE,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/schema:isPartOf[@xsi:type=schema:CreativeWorkSeries]/schema:hasPart",
)
bacp70 = MeemooSIPConstraint(
    "BACP70",
    "The name of the subseries. The `name` term MAY only be used multiple times when it uses a different language. The applied language MUST be provided by a `@xml:lang` attribute (see requirements above). If the element is present, there MUST always be an entry in Dutch with `@xml:lang` set to `nl`.",
    MeemooSIPConstraintCardinality.EXACTLY_ONE,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/schema:isPartOf[@xsi:type=schema:CreativeWorkSeries]/schema:hasPart/schema:name[@xml:lang=*]",
)
bacp71 = MeemooSIPConstraint(
    "BACP71",
    "Indicates a broadcast that this item is part of.",
    MeemooSIPConstraintCardinality.ZERO_OR_MORE,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/schema:isPartOf[@xsi:type=schema:BroadcastEvent]",
)
bacp72 = MeemooSIPConstraint(
    "BACP72",
    "The name of the broadcast. The `name` term MAY only be used multiple times when it uses a different language. The applied language MUST be provided by a `@xml:lang` attribute (see requirements above). If the element is present, there MUST always be an entry in Dutch with `@xml:lang` set to `nl`.",
    MeemooSIPConstraintCardinality.EXACTLY_ONE,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/schema:isPartOf[@xsi:type=schema:BroadcastEvent]/schema:name[@xml:lang=*]",
)
bacp73 = MeemooSIPConstraint(
    "BACP73",
    "Indicates a season that this item is part of.",
    MeemooSIPConstraintCardinality.ZERO_OR_MORE,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.UNSPECIFIED,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/schema:isPartOf[@xsi:type=schema:CreativeWorkSeason]",
)
bacp74 = MeemooSIPConstraint(
    "BACP74",
    "The name of the season. The `name` term MAY only be used multiple times when it uses a different language. The applied language MUST be provided by a `@xml:lang` attribute (see requirements above). If the element is present, there MUST always be an entry in Dutch with `@xml:lang` set to `nl`.",
    MeemooSIPConstraintCardinality.EXACTLY_ONE,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.STRING,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/schema:isPartOf[@xsi:type=schema:CreativeWorkSeason]/schema:name[@xml:lang=*]",
)
bacp75 = MeemooSIPConstraint(
    "BACP75",
    "Position of the season within an ordered group of seasons.",
    MeemooSIPConstraintCardinality.AT_MOST_ONE,
    MeemooSIPConstraintObligation.UNSPECIFIED,
    MeemooSIPConstraintSIPLevel.PACKAGE,
    MeemooSIPConstraintDatatype.INTEGER,
    MeemooSIPConstraintXMLNodeType.ELEMENT,
    "/metadata/descriptive/dc+schema.xml",
    "metadata/schema:isPartOf[@xsi:type=schema:CreativeWorkSeason]/schema:seasonNumber",
)
